### ISSUE TITLE
Run Kutt in development mode on Windows 10

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [thedevs-network/kutt#10]
ping @GingerPlusPlus @MKRhere @poeti8 @trgwii 

----

I ran the `npm run dev` command in CMD on Windows 10 with Node.js v6.11.0 and Neo4j Desktop 1.0.14.

I got this error output:

```
C:\Server\wamp64\www\~url-shortener\kutt>npm run dev

> kutt@1.0.0 dev C:\Server\wamp64\www\~url-shortener\kutt
> node ./server/server.js

C:\Server\wamp64\www\~url-shortener\kutt\server\controllers\authController.js:59
exports.recaptcha = async (req, res, next) => {
                          ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Server\wamp64\www\~url-shortener\kutt\server\server.js:10:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kutt@1.0.0 dev: `node ./server/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the kutt@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Suriyaa\AppData\Roaming\npm-cache\_logs\2018-02-18T15_23_28_018Z-debug.log

C:\Server\wamp64\www\~url-shortener\kutt>
```

My npm log file: [2018-02-18T15_23_28_018Z-debug.log](https://github.com/thedevs-network/kutt/files/1734825/2018-02-18T15_23_28_018Z-debug.log).

How can I fix this issue?

**Comment by GingerPlusPlus** [comment]
Node 6. That is your problem. Async functions appeared somewhere in Node 7. Upgrade to Node 8 or 9. If you don't wish to install it globally, if it's convinient for you to stay on old LTS, you can run the project like so: `npx node@9 server/server.js` or `npx node@latest server/server.js`, or, if you insist on using `npm run`, `npx -p node@9 -- npm run dev`.

**Comment by SuriyaaKudoIsc** [comment]
@GingerPlusPlus 👍 This works for me fine. Thanks a lot. 😄

**Comment by GingerPlusPlus** [comment]
Besides, **randomly** mentioning people like that is in my opinion rude, please don't. Next time, just post your issue and wait for someone to reply, @SuriyaaKudoIsc.

Note: it's not random if someone asks to be mentioned, or if you really know you need attention of a specific person or team.

**Comment by SuriyaaKudoIsc** [comment]
Ok. Sorry. 😬 😅
