### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Neo4jError: connect 

### ISSUE THREAD

**Issue by tavakoli-ali** [thedevs-network/kutt#156]
I have problem with connection between database and js

 UnhandledPromiseRejectionWarning: Neo4jError: connect ECONNREFUSED 0.0.0.0:7687

    at captureStacktrace (/Users/alitavakoli/Downloads/kutt-develop/node_modules/neo4j-driver/lib/v1/result.js:200:15)
    at new Result (/Users/alitavakoli/Downloads/kutt-develop/node_modules/neo4j-driver/lib/v1/result.js:73:19)
    at _newRunResult (/Users/alitavakoli/Downloads/kutt-develop/node_modules/neo4j-driver/lib/v1/transaction.js:342:10)
    at Object.run (/Users/alitavakoli/Downloads/kutt-develop/node_modules/neo4j-driver/lib/v1/transaction.js:251:14)
    at Transaction.run (/Users/alitavakoli/Downloads/kutt-develop/node_modules/neo4j-driver/lib/v1/transaction.js:120:26)
    at session.readTransaction.tx (/Users/alitavakoli/Downloads/kutt-develop/server/db/url.js:199:12)
    at TransactionExecutor._safeExecuteTransactionWork (/Users/alitavakoli/Downloads/kutt-develop/node_modules/neo4j-driver/lib/v1/internal/transaction-executor.js:136:22)
    at TransactionExecutor._executeTransactionInsidePromise (/Users/alitavakoli/Downloads/kutt-develop/node_modules/neo4j-driver/lib/v1/internal/transaction-executor.js:124:32)
    at Timeout._onTimeout (/Users/alitavakoli/Downloads/kutt-develop/node_modules/neo4j-driver/lib/v1/internal/transaction-executor.js:101:18)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
(node:6131) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:6131) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6131) UnhandledPromiseRejectionWarning: Neo4jError: connect ECONNREFUSED 0.0.0.0:7687

    at captureStacktrace (/Users/alitavakoli/Downloads/kutt-develop/node_modules/neo4j-driver/lib/v1/result.js:200:15)
    at new Result (/Users/alitavakoli/Downloads/kutt-develop/node_modules/neo4j-driver/lib/v1/result.js:73:19)
    at _newRunResult (/Users/alitavakoli/Downloads/kutt-develop/node_modules/neo4j-driver/lib/v1/transaction.js:342:10)
    at Object.run (/Users/alitavakoli/Downloads/kutt-develop/node_modules/neo4j-driver/lib/v1/transaction.js:251:14)
    at Transaction.run (/Users/alitavakoli/Downloads/kutt-develop/node_modules/neo4j-driver/lib/v1/transaction.js:120:26)
    at session.readTransaction.tx (/Users/alitavakoli/Downloads/kutt-develop/server/db/url.js:199:12)
    at TransactionExecutor._safeExecuteTransactionWork (/Users/alitavakoli/Downloads/kutt-develop/node_modules/neo4j-driver/lib/v1/internal/transaction-executor.js:136:22)
    at TransactionExecutor._executeTransactionInsidePromise (/Users/alitavakoli/Downloads/kutt-develop/node_modules/neo4j-driver/lib/v1/internal/transaction-executor.js:124:32)
    at Timeout._onTimeout (/Users/alitavakoli/Downloads/kutt-develop/node_modules/neo4j-driver/lib/v1/internal/transaction-executor.js:101:18)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)
(node:6131) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

**Comment by trgwii** [comment]
Is your database running?

**Comment by poeti8** [comment]
Either your database is not running or the credentials in the config file are not correct.
