### ISSUE TITLE
Struggling To Install

### ISSUE THREAD

**Issue by XiRealizeX** [thedevs-network/kutt#162]
I've spent over 5 hours trying to install this at least three times from scratch but I just can't get anything to work right with the super-basic instructions provided as well as a lack of consistent documentation available for the three main dependencies.

here is my error log when I run `npm run build`. Sorry if I'm vague but all I can say is that I've followed the necessary steps and **NOTHING** works. I'd appreciate if a _genius_ could help me get going.

I'm running Ubuntu Server 18.04.
Node.js, npm, Redis, Java & Neo4j are installed.

```js
root@fse-shortlink:/kutt/server# npm run build

> kutt@1.2.0 build /kutt
> next build ./client

[1:26:17 AM] Compiling client
[1:26:17 AM] Compiling server
> Using external babel configuration
> Location: "/kutt/.babelrc"
[1:26:24 AM] Compiled server in 7s
[1:26:27 AM] Compiled client in 10s
> Failed to build
{ Error: (client) ./components/BodyWrapper/BodyWrapper.js
Module not found: Error: Can't resolve '../../config' in '/kutt/client/components/BodyWrapper'
 @ ./components/BodyWrapper/BodyWrapper.js 29:0-51 53:10-29
 @ ./components/BodyWrapper/index.js
 @ ./pages/banned.js
 @ multi ./pages/banned.js
    at /kutt/node_modules/next/dist/build/index.js:144:31
    at finalCallback (/kutt/node_modules/webpack/lib/MultiCompiler.js:247:12)
    at runWithDependencies.err (/kutt/node_modules/webpack/lib/MultiCompiler.js:270:6)
    at done (/kutt/node_modules/neo-async/async.js:2928:13)
    at runCompilers (/kutt/node_modules/webpack/lib/MultiCompiler.js:174:48)
    at err (/kutt/node_modules/webpack/lib/MultiCompiler.js:181:7)
    at compiler.run (/kutt/node_modules/webpack/lib/MultiCompiler.js:263:7)
    at finalCallback (/kutt/node_modules/webpack/lib/Compiler.js:204:39)
    at hooks.done.callAsync.err (/kutt/node_modules/webpack/lib/Compiler.js:220:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/kutt/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:33:1)
    at AsyncSeriesHook.lazyCompileHook (/kutt/node_modules/tapable/lib/Hook.js:154:20)
    at onCompiled (/kutt/node_modules/webpack/lib/Compiler.js:218:21)
    at hooks.afterCompile.callAsync.err (/kutt/node_modules/webpack/lib/Compiler.js:547:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/kutt/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:15:1)
    at AsyncSeriesHook.lazyCompileHook (/kutt/node_modules/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/kutt/node_modules/webpack/lib/Compiler.js:544:30)
  errors:
   [ '(client) ./components/BodyWrapper/BodyWrapper.js\nModule not found: Error: Can\'t resolve \'../../config\' in \'/kutt/client/components/BodyWrapper\'\n @ ./components/BodyWrapper/BodyWrapper.js 29:0-51 53:10-29\n @ ./components/BodyWrapper/index.js\n @ ./pages/banned.js\n @ multi ./pages/banned.js',
     '(client) ./components/Footer/Footer.js\nModule not found: Error: Can\'t resolve \'../../config\' in \'/kutt/client/components/Footer\'\n @ ./components/Footer/Footer.js 25:0-34 73:26-32 74:31-37\n @ ./pages/index.js\n @ multi ./pages/index.js',
     '(client) ./components/Footer/ReCaptcha.js\nModule not found: Error: Can\'t resolve \'../../config\' in \'/kutt/client/components/Footer\'\n @ ./components/Footer/ReCaptcha.js 3:0-34 13:20-26\n @ ./components/Footer/Footer.js\n @ ./pages/index.js\n @ multi ./pages/index.js',
     '(client) ./helpers/analytics.js\nModule not found: Error: Can\'t resolve \'../config\' in \'/kutt/client/helpers\'\n @ ./helpers/analytics.js 2:0-48 4:21-40\n @ ./components/BodyWrapper/BodyWrapper.js\n @ ./components/BodyWrapper/index.js\n @ ./pages/banned.js\n @ multi ./pages/banned.js',
     '(client) ./pages/report.js\nModule not found: Error: Can\'t resolve \'../config\' in \'/kutt/client/pages\'\n @ ./pages/report.js 30:0-41 157:318-330\n @ multi ./pages/report.js',
     '(server) ./components/BodyWrapper/BodyWrapper.js\nModule not found: Error: Can\'t resolve \'../../config\' in \'/kutt/client/components/BodyWrapper\'\n @ ./components/BodyWrapper/BodyWrapper.js 29:0-51 53:10-29\n @ ./components/BodyWrapper/index.js\n @ ./pages/banned.js\n @ multi ./pages/banned.js',
     '(server) ./components/Footer/Footer.js\nModule not found: Error: Can\'t resolve \'../../config\' in \'/kutt/client/components/Footer\'\n @ ./components/Footer/Footer.js 25:0-34 73:26-32 74:31-37\n @ ./pages/index.js\n @ multi ./pages/index.js',
     '(server) ./components/Footer/ReCaptcha.js\nModule not found: Error: Can\'t resolve \'../../config\' in \'/kutt/client/components/Footer\'\n @ ./components/Footer/ReCaptcha.js 3:0-34 13:20-26\n @ ./components/Footer/Footer.js\n @ ./pages/index.js\n @ multi ./pages/index.js',
     '(server) ./helpers/analytics.js\nModule not found: Error: Can\'t resolve \'../config\' in \'/kutt/client/helpers\'\n @ ./helpers/analytics.js 2:0-48 4:21-40\n @ ./components/BodyWrapper/BodyWrapper.js\n @ ./components/BodyWrapper/index.js\n @ ./pages/banned.js\n @ multi ./pages/banned.js',
     '(server) ./pages/report.js\nModule not found: Error: Can\'t resolve \'../config\' in \'/kutt/client/pages\'\n @ ./pages/report.js 30:0-41 157:318-330\n @ multi ./pages/report.js' ],
  warnings: [] }

```

**Comment by RusseII** [comment]
I have the same issue.

**Comment by RusseII** [comment]
I figured it out.

Add a file /client/config.js

Put the following inside the config.js file
```
module.exports = {
  /*
    Invisible reCaptcha site key
    Create one in https://www.google.com/recaptcha/intro/
  */
  RECAPTCHA_SITE_KEY: '',

  // Google analytics tracking ID
  GOOGLE_ANALYTICS_ID: '6Lc4TUAUAAAAAMRHnlEEt21UkPlOXKCXHaIapdTT',

  // Contact email address
  CONTACT_EMAIL: '',

  // Report email address
  REPORT_EMAIL: '',
};
```

**Comment by poeti8** [comment]
@XiRealizeX Did you read step 2? It clearly says to copy `config.example.js` to `config.js` and then edit the file, and yet you're running the app without a `config.js` file.

**Comment by DRSchlaubi** [comment]
But where is the config.example.js?

**Comment by poeti8** [comment]
@DRSchlaubi This is deprecated. You only need to have a .env file with configurations inside. Please also read the wiki for the full instructions and let me know if you had questions.

**Comment by DRSchlaubi** [comment]
But in the wiki you wrote `Pull the code from the repository. Now copy both config.example.js files to config.js in their folders respectively and fill them based on the comments inside them. Install dependencies and build the app by running the next commands while you're in the root folder:` [link](https://github.com/thedevs-network/kutt/wiki/Setup-and-deployment#config)

**Comment by poeti8** [comment]
Oops, forgot to update that part of the wiki. Edited now. Thanks.
