### ISSUE TITLE
How does one create these indexes from CLI in neo4j

### ISSUE THREAD

**Issue by uhlhosting** [thedevs-network/kutt#172]
https://github.com/thedevs-network/kutt/wiki/Setup-and-deployment#assing-indexes-and-constraints

```
Connected to Neo4j 3.5.5 at bolt://localhost:7687 as user neo4j.
Type :help for a list of available commands or :exit to exit the shell.
Note that Cypher queries must end with a semicolon.
neo4j> :help

Available commands:
  :begin    Open a transaction
  :commit   Commit the currently open transaction
  :exit     Exit the logger
  :help     Show this help message
  :history  Print a list of the last commands executed
  :param    Set the value of a query parameter
  :params   Prints all currently set query parameters and their values
  :rollback Rollback the currently open transaction

For help on a specific command type:
    :help command


For help on cypher please visit:
    https://neo4j.com/docs/developer-manual/current/cypher/

neo4j> 

```

**Comment by poeti8** [comment]
What's the problem? You're in Cypher Shell, you can run Cypher queries now.
https://neo4j.com/docs/operations-manual/current/tools/cypher-shell/

**Comment by uhlhosting** [comment]
I managed to run the queries, anyhow is not clear to me, why nothing works on my site: https://uhl.site all seems to throw this on console:

```
root@for:/home/cosmic/kutt-develop# pm2 logs Kutt [--lines 1000]
[TAILING] Tailing last 15 lines for [Kutt] process (change the value with --lines option)
/root/.pm2/logs/Kutt-out.log last 15 lines:
0|Kutt     | > Ready on http://localhost:3000

/root/.pm2/logs/Kutt-error.log last 15 lines:
0|Kutt     | node_redis: Warning: Redis server does not require a password, but a password was supplied.
0|Kutt     | Error: Error: 140013574232960:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:827:
0|Kutt     | 
0|Kutt     |     at fn.catch.err (/home/cosmic/kutt-develop/server/server.js:32:13)
0|Kutt     |     at <anonymous>
0|Kutt     |     at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```
