### ISSUE TITLE
Docker-compose fails to starts

### ISSUE THREAD

**Issue by alessandro308** [thedevs-network/kutt#240]
I'm trying to execute the containers on my machine:
```
mv .example.env .env
docker-compose up
```

returns the following error:
```
Starting postgres ... done
Starting redis    ... done
Starting kutt     ... done
Attaching to postgres, redis, kutt
postgres    |
postgres    | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres    |
postgres    | 2019-12-09 16:20:52.429 UTC [1] LOG:  starting PostgreSQL 12.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
postgres    | 2019-12-09 16:20:52.429 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres    | 2019-12-09 16:20:52.429 UTC [1] LOG:  listening on IPv6 address "::", port 5432
postgres    | 2019-12-09 16:20:52.432 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
redis       | 1:C 09 Dec 2019 16:20:52.398 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis       | 1:C 09 Dec 2019 16:20:52.398 # Redis version=5.0.7, bits=64, commit=00000000, modified=0, pid=1, just started
redis       | 1:C 09 Dec 2019 16:20:52.398 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
redis       | 1:M 09 Dec 2019 16:20:52.399 * Running mode=standalone, port=6379.
redis       | 1:M 09 Dec 2019 16:20:52.399 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis       | 1:M 09 Dec 2019 16:20:52.399 # Server initialized
redis       | 1:M 09 Dec 2019 16:20:52.399 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
redis       | 1:M 09 Dec 2019 16:20:52.399 * DB loaded from disk: 0.000 seconds
redis       | 1:M 09 Dec 2019 16:20:52.399 * Ready to accept connections
postgres    | 2019-12-09 16:20:52.454 UTC [21] LOG:  database system was shut down at 2019-12-09 16:20:37 UTC
postgres    | 2019-12-09 16:20:52.458 UTC [1] LOG:  database system is ready to accept connections
kutt        |
kutt        | > kutt@2.1.7 start /usr/src/app
kutt        | > NODE_ENV=production node production-server/server.js
kutt        |
kutt        | events.js:187
kutt        |       throw er; // Unhandled 'error' event
kutt        |       ^
kutt        |
kutt        | Error: Redis connection to "127.0.0.1":6379 failed - getaddrinfo ENOTFOUND "127.0.0.1"
kutt        |     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26)
kutt        | Emitted 'error' event on RedisClient instance at:
kutt        |     at RedisClient.on_error (/usr/src/app/node_modules/redis/index.js:406:14)
kutt        |     at Socket.<anonymous> (/usr/src/app/node_modules/redis/index.js:279:14)
kutt        |     at Socket.emit (events.js:210:5)
kutt        |     at Socket.EventEmitter.emit (domain.js:475:20)
kutt        |     at emitErrorNT (internal/streams/destroy.js:92:8)
kutt        |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
kutt        |     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
kutt        |   errno: 'ENOTFOUND',
kutt        |   code: 'ENOTFOUND',
kutt        |   syscall: 'getaddrinfo',
kutt        |   hostname: '"127.0.0.1"'
kutt        | }
kutt        | npm ERR! code ELIFECYCLE
kutt        | npm ERR! errno 1
kutt        | npm ERR! kutt@2.1.7 start: `NODE_ENV=production node production-server/server.js`
kutt        | npm ERR! Exit status 1
kutt        | npm ERR!
kutt        | npm ERR! Failed at the kutt@2.1.7 start script.
kutt        | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
kutt        |
kutt        | npm ERR! A complete log of this run can be found in:
kutt        | npm ERR!     /root/.npm/_logs/2019-12-09T16_20_54_532Z-debug.log
kutt exited with code 1
```

Any help?

**Comment by poeti8** [comment]
The config in .env file is wrong. You should fill it with correct info.
