### ISSUE TITLE
Connection to Redis cannot be established on Docker

### ISSUE THREAD

**Issue by raisty** [thedevs-network/kutt#261]
Seems like something is with a connection between Redis and Application. I cannot establish a connection. I tried to play with settings, but no success.

I am using Kutt development version with Docker on Ubuntu.

```
> kutt@2.1.7 start /usr/src/app
> NODE_ENV=production node production-server/server.js

events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)
Emitted 'error' event on RedisClient instance at:
    at RedisClient.on_error (/usr/src/app/node_modules/redis/index.js:406:14)
    at Socket.<anonymous> (/usr/src/app/node_modules/redis/index.js:279:14)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
    errno: 'ECONNREFUSED',
    code: 'ECONNREFUSED',
    syscall: 'connect',
    address: '127.0.0.1',
    port: 6379
    }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kutt@2.1.7 start: `NODE_ENV=production node production-server/server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kutt@2.1.7 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by poeti8** [comment]
Make sure `.env` is filled with correct value. In Docker environment `REDIS_HOST` needs to be set to `redis` instead of localhost.

**Comment by HarasimowiczKamil** [comment]
I have this same issue. Change host to `redis` not help. I try add:
```yaml
ports:
      - "6379:6379"
```
to redis section but this not change anything. But then, connection from host to redis is possible.

**Comment by jk779** [comment]
@HarasimowiczKamil skip the `"` in .env so that it reads 
```
REDIS_HOST=redis
```
now it should work
