### ISSUE TITLE
Permission denied to create extension "uuid-ossp"

### ISSUE THREAD

**Issue by nightah** [thedevs-network/kutt#264]
After updating to HEAD and building a new container, upon startup the following is seen in the logs:
```
(node:18) UnhandledPromiseRejectionWarning: error: permission denied to create extension "uuid-ossp"
    at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:604:11)
    at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:401:19)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at addChunk (_stream_readable.js:308:12)
> kutt@2.2.10 start /usr/src/app
> NODE_ENV=production node production-server/server.js

    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by poeti8** [comment]
Make sure your database user has access to install extension on Postgres.

**Comment by nightah** [comment]
I just added the extension manually with the root user so I didn't need to elevate access on the specified account, thanks.

**Comment by donnib** [comment]
I have this issue, could somebody explain how to grant user "install extension" privileges on Postgres ?
