### ISSUE TITLE
Failed at the husky@0.15.0-rc.13 install script

### ISSUE THREAD

**Issue by strasharo** [thedevs-network/kutt#297]
Trying to install on 18.04 Ubuntu with nodejs lts and getting the following error:
```

root@aekutt:~/kutt# npm install

> husky@0.15.0-rc.13 install /root/kutt/node_modules/husky
> node lib/installer/bin install

internal/modules/cjs/loader.js:985
  throw err;
  ^

Error: Cannot find module '/root/kutt/node_modules/husky/lib/installer/bin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fork-ts-checker-webpack-plugin/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! husky@0.15.0-rc.13 install: `node lib/installer/bin install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the husky@0.15.0-rc.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-02T17_54_53_656Z-debug.log
root@aekutt:~/kutt#
```
Any idea what might be wrong?

**Comment by ProfessorVarox** [comment]
have the same problem when I try to install it in Plesk
