### ISSUE TITLE
Trying to npm run -- errors

### ISSUE THREAD

**Issue by Moehrenbaum** [thedevs-network/kutt#302]
- I have all components (postgres and redis in docker) started and ready to connect. 
- Check connections manually -- all available 
- Updated all (Ubuntu 19.x, NodeJs ...)

**npm run** creates this. No idea what else I can look for. trying for hours by now. I would assume it tries to run a script to setup the initial DB?

**DB was setup like this**
docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d postgres

**Any help is appreciated.**

> knex migrate:up --env production

Requiring external module @babel/register
Using environment: production
TimeoutError: Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?
    at /home/dirklx/kutt/node_modules/knex/lib/client.js:318:17
    at tryCatcher (/home/dirklx/kutt/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at /home/dirklx/kutt/node_modules/knex/node_modules/bluebird/js/release/catch_filter.js:17:41
    at tryCatcher (/home/dirklx/kutt/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/dirklx/kutt/node_modules/knex/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/dirklx/kutt/node_modules/knex/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/dirklx/kutt/node_modules/knex/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/dirklx/kutt/node_modules/knex/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/dirklx/kutt/node_modules/knex/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/dirklx/kutt/node_modules/knex/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/dirklx/kutt/node_modules/knex/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/dirklx/kutt/node_modules/knex/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kutt@2.3.14 migrate: `knex migrate:up --env production`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kutt@2.3.14 migrate script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dirklx/.npm/_logs/2020-04-22T19_16_37_915Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kutt@2.3.14 dev: `npm run migrate && nodemon server/server.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kutt@2.3.14 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dirklx/.npm/_logs/2020-04-22T19_16_37_937Z-debug.log
dirklx@eresponder-urlshortener:~/kutt$

**Comment by MKRhere** [comment]
Since it's been a while, were you able to resolve this or still require assistance?
