### ISSUE TITLE
DB Password Authentication Fails

### ISSUE THREAD

**Issue by Austinn-JS** [thedevs-network/kutt#478]
In all files used by docker-compose (including .env) the password and user are the same. But when I build and start it, it gives this issue:
`error: password authentication failed for user "kuttlinks"
    at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/src/parser.ts:325:11)
    at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/src/parser.ts:154:21)
    at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:106:30)
    at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)`
    
I did not change anything related to the DB other than the Authentication Information.

Any help is appreciated.

**Comment by Austinn-JS** [comment]
Fixed the issue.

**Comment by poeti8** [comment]
@Austinn-JS what was the issue?

**Comment by ajz007** [comment]
I faced a similar issue. I had already done the docker setup and was able to login successfully but, now I wanted to explore the code. So, I cloned the code and ran: npm run dev
and was getting similar error related to authentication.
On investigation I could see that on startup the application is trying to connect to the database instance and since its not able to authenticate the user its giving this error.
In the .env file we have to give the correct credentials for the database. if you dont give the correct user name it basically picks the system user and tries to authenticate against the database and fails. So, to fix the issue ensure that the db details are correct.
If anyone is running a similar setup as mine ie; the database and redis are in docker then please check the docker-compose.yml file for database and redis details.

Hope this helps.
