### ISSUE TITLE
password authentication failed for user (1st startup)

### ISSUE THREAD

**Issue by kwschnei** [thedevs-network/kutt#528]
Using the stock docker-compose.yml file and only the described minimal edits to .env, first startup fails with the following error:

kutt_1      | Using environment: production
postgres_1  | 2021-10-18 00:26:34.089 UTC [29] FATAL:  password authentication failed for user "user"
postgres_1  | 2021-10-18 00:26:34.089 UTC [29] DETAIL:  Password does not match for user "user".
postgres_1  | 	Connection matched pg_hba.conf line 99: "host all all all md5"
kutt_1      | error: password authentication failed for user "user"
kutt_1      |     at Parser.parseErrorMessage (/usr/src/app/node_modules/pg-protocol/src/parser.ts:325:11)
kutt_1      |     at Parser.handlePacket (/usr/src/app/node_modules/pg-protocol/src/parser.ts:154:21)
kutt_1      |     at Parser.parse (/usr/src/app/node_modules/pg-protocol/src/parser.ts:106:30)
kutt_1      |     at Socket.<anonymous> (/usr/src/app/node_modules/pg-protocol/src/index.ts:7:48)
kutt_1      |     at Socket.emit (events.js:314:20)
kutt_1      |     at Socket.EventEmitter.emit (domain.js:483:12)
kutt_1      |     at addChunk (_stream_readable.js:297:12)
kutt_1      |     at readableAddChunk (_stream_readable.js:272:9)
kutt_1      |     at Socket.Readable.push (_stream_readable.js:213:10)
kutt_1      |     at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
kutt_1      | npm ERR! code ELIFECYCLE
kutt_1      | npm ERR! errno 1
kutt_1      | npm ERR! kutt@2.7.3 migrate: `knex migrate:latest --env production`
kutt_1      | npm ERR! Exit status 1
kutt_1      | npm ERR! 
kutt_1      | npm ERR! Failed at the kutt@2.7.3 migrate script.
kutt_1      | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
kutt_1      | 
kutt_1      | npm ERR! A complete log of this run can be found in:
kutt_1      | npm ERR!     /root/.npm/_logs/2021-10-18T00_26_34_129Z-debug.log
kutt_1      | npm ERR! code ELIFECYCLE
kutt_1      | npm ERR! errno 1
kutt_1      | npm ERR! kutt@2.7.3 start: `npm run migrate && cross-env NODE_ENV=production node production-server/server.js`
kutt_1      | npm ERR! Exit status 1
kutt_1      | npm ERR! 
kutt_1      | npm ERR! Failed at the kutt@2.7.3 start script.
kutt_1      | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
kutt_1      | 
kutt_1      | npm ERR! A complete log of this run can be found in:
kutt_1      | npm ERR!     /root/.npm/_logs/2021-10-18T00_26_34_148Z-debug.log
kutt_kutt_1 exited with code 1

**Comment by dezerving** [comment]
I have the same exact issue. Did you ever find a solution?

**Comment by kwschnei** [comment]
No - I gave up and switched to [Polr](https://github.com/Cydrobolt/polr).

**Comment by dezerving** [comment]
> No - I gave up and switched to [Polr](https://github.com/Cydrobolt/polr).

I'm gonna give Polr a go then. Since this is not working and I can't find anything to fix this lol.

**Comment by Ritbit** [comment]
Thanks for the tip on polr.. I also could not net Kutt to accept new users... so I gave up too.. 
The project seems dead anyway..

**Comment by poeti8** [comment]
I think your Postgres credentials are wrong. Make sure you have created users with correct access on your database first and then update `.env` with your database's credentials.

**Comment by imadmoussa1** [comment]
@poeti8 Yes this worked for me, when using docker compose the password are set in the compose file and not in the .env file
