### ISSUE TITLE
Error : Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by pradt** [thedevs-network/kutt#725]
I'm trying to run kutt on a ubuntu server using npm run dev, I've updated the .env and the main things that were ommitted were the recaptcha and Google Analytics which I have commented out. Postgres and redis are up and running. I'm getting the following error which I'm not sure how to resolve - I'm also using node 18 not sure of the exact version to run kutt under. 

`> kutt@2.7.4 dev
> npm run migrate && cross-env NODE_ENV=development nodemon server/server.ts

> kutt@2.7.4 migrate
> knex migrate:latest --env production

Requiring external module ts-node/register
Using environment: production
Batch 1 run: 5 migrations
[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): server/**/*.ts
[nodemon] watching extensions: ts,json
[nodemon] starting `rimraf production-server && tsc --project tsconfig.json && copyfiles -f "server/mail/*.html" production-server/mail && node production-server/server.js server/server.ts`
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/prad/kutt-2.7.4/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at processResource (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:208:3)
    at iteratePitchingLoaders (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at iteratePitchingLoaders (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/prad/kutt-2.7.4/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at processResource (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:208:3)
    at iteratePitchingLoaders (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:158:10)
    at iteratePitchingLoaders (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
[2023-11-28 13:52:35] error: uncaughtException: error:0308010C:digital envelope routines::unsupported
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/prad/kutt-2.7.4/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/prad/kutt-2.7.4/node_modules/next/dist/compiled/babel-loader/index.js:1:3616
[2023-11-28 13:52:35] error: uncaughtException: error:0308010C:digital envelope routines::unsupported
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/prad/kutt-2.7.4/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/prad/kutt-2.7.4/node_modules/next/dist/compiled/babel-loader/index.js:1:3616
[2023-11-28 13:52:35] error: uncaughtException: error:0308010C:digital envelope routines::unsupported
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/prad/kutt-2.7.4/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/prad/kutt-2.7.4/node_modules/next/dist/compiled/babel-loader/index.js:1:3616
[2023-11-28 13:52:35] error: uncaughtException: error:0308010C:digital envelope routines::unsupported
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/prad/kutt-2.7.4/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/prad/kutt-2.7.4/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/prad/kutt-2.7.4/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/prad/kutt-2.7.4/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
[2023-11-28 13:52:35] error: uncaughtException: error:0308010C:digital envelope routines::unsupported
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/home/prad/kutt-2.7.4/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/prad/kutt-2.7.4/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/prad/kutt-2.7.4/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/prad/kutt-2.7.4/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/prad/kutt-2.7.4/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /home/prad/kutt-2.7.4/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)`

Have i missed a setting ?

**Comment by mena-heero** [comment]
Maybe the issue is about Node version, I'd Would Suggest Considering Using Docker Instead

**Comment by Nathan-Roberts123** [comment]
I have exactly the same configuration as you but I am using node 15 and it works. I stoped using node 18 cause I kept getting errors when I was running `npm install`.

**Comment by waclaw66** [comment]
Same problem with Node 20, seems this project is no longer maintained.

**Comment by panta82** [comment]
This helps:
```
export NODE_OPTIONS=--openssl-legacy-provider
```
