### ISSUE TITLE
Reverse Proxy Support

### ISSUE THREAD

**Issue by nightah** [thedevs-network/kutt#80]
I've installed kutt and attempted to run the master behind my own nginx SSL enabled reverse proxy and I can't seem to get the root path 'https://example.com/' to work. I keep getting redirect errors.

All other URI's appear to work like /login /logout /settings etc if I explicitly browse to them.

It also appears that when trying to actually submit a link to be shortened the kutt server returns the following:

```
(node:18) UnhandledPromiseRejectionWarning: Error: Error: Request failed with status code 403
    at fn.catch.err (/code/server/server.js:34:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:18) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Is there some sort of special configuration is required to occur to support a RP in front of kutt?

**Comment by poeti8** [comment]
No special configuration, you must just make sure that you have filled all the options in both `config.js` files inside server and client folders.
This could also because of not being connected to a Neo4j database.

**Comment by nightah** [comment]
The only option that isn't filled in is the RECAPTCHA codes, so all of these are mandatory?

That might explain the second part perhaps, but it doesn't explain why hitting the server root results in an endless redirect loop.

I can access the neo4j instance both inside the container network and outside so I don't think it's that.

Can I perhaps provide more detail to try and identify the redirection loop issue?

**Comment by poeti8** [comment]
Yes all of them are mandatory.
Does login / sign up work?

**Comment by nightah** [comment]
Yes I'm able to sign up, I also receive the verification email because I setup a mailserver and subsequently am able to login too.

**Comment by nightah** [comment]
The problem with the endless redirect loop on the root URI was because the Host header being passed back to kutt was `$host:$port` and this didn't match the `DEFAULT_DOMAIN`.
This also caused any of the redirect pages to not work. Once I resolved this in my reverse proxy configuration this resolved the issue.

**Comment by ne0c0de** [comment]
Hi

I have a question about reverse proxy.

I'm running Kutt on 3000 port on server, and put a reverse proxy support to my current nodejs app (which is open to world on 80 port) by adding this line:

```
app.use('/url', proxy('kutt.mydomain.com:3000'));
```

It works fine on homepage and redirection service but login and other sub pages are getting 404 error because it's trying to load all static files and other paths to root.

For example:

my own express app domain:
www.mydomain.com

Kutt domain: kutt.mydomain.com

once I go to www.mydomain.com/url express app route my requests to Kutt app directly. But the above problem arise on this stage. How can I resolve it?

**Comment by trgwii** [comment]
We're currently working towards solving this, it should be possible to set up a URL rewrite rule for your reverse proxy in the meantime (rewrite /url to /)
