### ISSUE TITLE
Dockerfile not building

### ISSUE THREAD

**Issue by silver0a1** [thedevs-network/kutt#86]
Using the following command:
docker build -t kutt .
Seems to error out on babel

Attempted on ContainerOS on Google Compute

**Comment by trgwii** [comment]
What's the error?

**Comment by m3adow** [comment]
While I am not the original reporter of the issue, I also encountered errors when trying to build the Dockerfile.

I don't think it's relevant, but I'm running Docker CE 18.06.1 on Ubuntu 18.04.1

```bash
~$ docker build -t kutt .
Sending build context to Docker daemon  1.127MB
Step 1/6 : FROM node:9.5.0-alpine
 ---> e90a5bfd29f6
Step 2/6 : ADD . /code
 ---> Using cache
 ---> f43ebca0576f
Step 3/6 : WORKDIR /code
 ---> Using cache
 ---> 4143b0f3fd06
Step 4/6 : RUN npm install
 ---> Using cache
 ---> 09da90ee8f21
Step 5/6 : RUN npm run build
 ---> Running in 632ded113350

> kutt@1.0.0 build /code
> next build ./client

> Using external babel configuration
> Location: "/code/.babelrc"
> Failed to build
{ Error: (client) ./client/components/BodyWrapper/BodyWrapper.js
Module not found: Error: Can't resolve '../../config' in '/code/client/components/BodyWrapper'
resolve '../../config' in '/code/client/components/BodyWrapper'
  using description file: /code/package.json (relative path: ./client/components/BodyWrapper)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /code/package.json (relative path: ./client/components/BodyWrapper)
    using description file: /code/package.json (relative path: ./client/config)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /code/client/config doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /code/client/config.js doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        /code/client/config.jsx doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /code/client/config.json doesn't exist
      as directory
        /code/client/config doesn't exist
[/code/client/config]
[/code/client/config.js]
[/code/client/config.jsx]
[/code/client/config.json]
[/code/client/config]
 @ ./client/components/BodyWrapper/BodyWrapper.js 41:14-37
 @ ./client/components/BodyWrapper/index.js
 @ ./client/pages/index.js
 @ multi ./pages/index.js
    at /code/node_modules/next/dist/server/build/index.js:162:31
    at runWithDependencies (/code/node_modules/webpack/lib/MultiCompiler.js:154:4)
    at /code/node_modules/async/dist/async.js:1126:9
    at /code/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/code/node_modules/async/dist/async.js:1050:13)
    at /code/node_modules/async/dist/async.js:958:16
    at /code/node_modules/async/dist/async.js:1123:13
    at runCompilers (/code/node_modules/webpack/lib/MultiCompiler.js:96:47)
    at fn (/code/node_modules/webpack/lib/MultiCompiler.js:101:6)
    at compiler.run (/code/node_modules/webpack/lib/MultiCompiler.js:150:5)
    at emitRecords.err (/code/node_modules/webpack/lib/Compiler.js:265:13)
    at Compiler.emitRecords (/code/node_modules/webpack/lib/Compiler.js:371:38)
    at emitAssets.err (/code/node_modules/webpack/lib/Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (/code/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/code/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/code/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
  errors: 
   [ '(client) ./client/components/BodyWrapper/BodyWrapper.js\nModule not found: Error: Can\'t resolve \'../../config\' in \'/code/client/components/BodyWrapper\'\nresolve \'../../config\' in \'/code/client/components/BodyWrapper\'\n  using description file: /code/package.json (relative path: ./client/components/BodyWrapper)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /code/package.json (relative path: ./client/components/BodyWrapper)\n    using description file: /code/package.json (relative path: ./client/config)\n      no extension\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config doesn\'t exist\n      .js\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.js doesn\'t exist\n      .jsx\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.jsx doesn\'t exist\n      .json\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.json doesn\'t exist\n      as directory\n        /code/client/config doesn\'t exist\n[/code/client/config]\n[/code/client/config.js]\n[/code/client/config.jsx]\n[/code/client/config.json]\n[/code/client/config]\n @ ./client/components/BodyWrapper/BodyWrapper.js 41:14-37\n @ ./client/components/BodyWrapper/index.js\n @ ./client/pages/index.js\n @ multi ./pages/index.js',
     '(client) ./client/components/Footer/ReCaptcha.js\nModule not found: Error: Can\'t resolve \'../../config\' in \'/code/client/components/Footer\'\nresolve \'../../config\' in \'/code/client/components/Footer\'\n  using description file: /code/package.json (relative path: ./client/components/Footer)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /code/package.json (relative path: ./client/components/Footer)\n    using description file: /code/package.json (relative path: ./client/config)\n      no extension\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config doesn\'t exist\n      .js\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.js doesn\'t exist\n      .jsx\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.jsx doesn\'t exist\n      .json\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.json doesn\'t exist\n      as directory\n        /code/client/config doesn\'t exist\n[/code/client/config]\n[/code/client/config.js]\n[/code/client/config.jsx]\n[/code/client/config.json]\n[/code/client/config]\n @ ./client/components/Footer/ReCaptcha.js 15:14-37\n @ ./client/components/Footer/Footer.js\n @ ./client/pages/index.js\n @ multi ./pages/index.js',
     '(client) ./client/helpers/analytics.js\nModule not found: Error: Can\'t resolve \'../config\' in \'/code/client/helpers\'\nresolve \'../config\' in \'/code/client/helpers\'\n  using description file: /code/package.json (relative path: ./client/helpers)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /code/package.json (relative path: ./client/helpers)\n    using description file: /code/package.json (relative path: ./client/config)\n      no extension\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config doesn\'t exist\n      .js\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.js doesn\'t exist\n      .jsx\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.jsx doesn\'t exist\n      .json\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.json doesn\'t exist\n      as directory\n        /code/client/config doesn\'t exist\n[/code/client/config]\n[/code/client/config.js]\n[/code/client/config.jsx]\n[/code/client/config.json]\n[/code/client/config]\n @ ./client/helpers/analytics.js 12:14-34\n @ ./client/components/BodyWrapper/BodyWrapper.js\n @ ./client/components/BodyWrapper/index.js\n @ ./client/pages/index.js\n @ multi ./pages/index.js',
     '(client) ./client/pages/report.js\nModule not found: Error: Can\'t resolve \'../config\' in \'/code/client/pages\'\nresolve \'../config\' in \'/code/client/pages\'\n  using description file: /code/package.json (relative path: ./client/pages)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /code/package.json (relative path: ./client/pages)\n    using description file: /code/package.json (relative path: ./client/config)\n      no extension\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config doesn\'t exist\n      .js\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.js doesn\'t exist\n      .jsx\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.jsx doesn\'t exist\n      .json\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.json doesn\'t exist\n      as directory\n        /code/client/config doesn\'t exist\n[/code/client/config]\n[/code/client/config.js]\n[/code/client/config.jsx]\n[/code/client/config.json]\n[/code/client/config]\n @ ./client/pages/report.js 29:14-34\n @ multi ./pages/report.js',
     '(server) ./client/components/BodyWrapper/BodyWrapper.js\nModule not found: Error: Can\'t resolve \'../../config\' in \'/code/client/components/BodyWrapper\'\nresolve \'../../config\' in \'/code/client/components/BodyWrapper\'\n  using description file: /code/package.json (relative path: ./client/components/BodyWrapper)\n  after using description file: /code/package.json (relative path: ./client/components/BodyWrapper)\n    using description file: /code/package.json (relative path: ./client/config)\n      no extension\n        /code/client/config doesn\'t exist\n      .js\n        /code/client/config.js doesn\'t exist\n      .jsx\n        /code/client/config.jsx doesn\'t exist\n      .json\n        /code/client/config.json doesn\'t exist\n      as directory\n        /code/client/config doesn\'t exist\n[/code/client/config]\n[/code/client/config.js]\n[/code/client/config.jsx]\n[/code/client/config.json]\n[/code/client/config]\n @ ./client/components/BodyWrapper/BodyWrapper.js 41:14-37\n @ ./client/components/BodyWrapper/index.js\n @ ./client/pages/index.js\n @ multi ./pages/index.js',
     '(server) ./client/components/Footer/ReCaptcha.js\nModule not found: Error: Can\'t resolve \'../../config\' in \'/code/client/components/Footer\'\nresolve \'../../config\' in \'/code/client/components/Footer\'\n  using description file: /code/package.json (relative path: ./client/components/Footer)\n  after using description file: /code/package.json (relative path: ./client/components/Footer)\n    using description file: /code/package.json (relative path: ./client/config)\n      no extension\n        /code/client/config doesn\'t exist\n      .js\n        /code/client/config.js doesn\'t exist\n      .jsx\n        /code/client/config.jsx doesn\'t exist\n      .json\n        /code/client/config.json doesn\'t exist\n      as directory\n        /code/client/config doesn\'t exist\n[/code/client/config]\n[/code/client/config.js]\n[/code/client/config.jsx]\n[/code/client/config.json]\n[/code/client/config]\n @ ./client/components/Footer/ReCaptcha.js 15:14-37\n @ ./client/components/Footer/Footer.js\n @ ./client/pages/index.js\n @ multi ./pages/index.js',
     '(server) ./client/helpers/analytics.js\nModule not found: Error: Can\'t resolve \'../config\' in \'/code/client/helpers\'\nresolve \'../config\' in \'/code/client/helpers\'\n  using description file: /code/package.json (relative path: ./client/helpers)\n  after using description file: /code/package.json (relative path: ./client/helpers)\n    using description file: /code/package.json (relative path: ./client/config)\n      no extension\n        /code/client/config doesn\'t exist\n      .js\n        /code/client/config.js doesn\'t exist\n      .jsx\n        /code/client/config.jsx doesn\'t exist\n      .json\n        /code/client/config.json doesn\'t exist\n      as directory\n        /code/client/config doesn\'t exist\n[/code/client/config]\n[/code/client/config.js]\n[/code/client/config.jsx]\n[/code/client/config.json]\n[/code/client/config]\n @ ./client/helpers/analytics.js 12:14-34\n @ ./client/components/BodyWrapper/BodyWrapper.js\n @ ./client/components/BodyWrapper/index.js\n @ ./client/pages/index.js\n @ multi ./pages/index.js',
     '(server) ./client/pages/report.js\nModule not found: Error: Can\'t resolve \'../config\' in \'/code/client/pages\'\nresolve \'../config\' in \'/code/client/pages\'\n  using description file: /code/package.json (relative path: ./client/pages)\n  after using description file: /code/package.json (relative path: ./client/pages)\n    using description file: /code/package.json (relative path: ./client/config)\n      no extension\n        /code/client/config doesn\'t exist\n      .js\n        /code/client/config.js doesn\'t exist\n      .jsx\n        /code/client/config.jsx doesn\'t exist\n      .json\n        /code/client/config.json doesn\'t exist\n      as directory\n        /code/client/config doesn\'t exist\n[/code/client/config]\n[/code/client/config.js]\n[/code/client/config.jsx]\n[/code/client/config.json]\n[/code/client/config]\n @ ./client/pages/report.js 29:14-34\n @ multi ./pages/report.js' ],
  warnings: [] }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kutt@1.0.0 build: `next build ./client`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kutt@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-10-04T05_53_28_376Z-debug.log
The command '/bin/sh -c npm run build' returned a non-zero code: 1
```
