### ISSUE TITLE
Docker Build Failed

### ISSUE THREAD

**Issue by l0nax** [thedevs-network/kutt#93]
Link to the old Issue (where is no Build Error Log): #86 

Here is the Build Output of Docker:
```bash
root@p200300EEEE:~/kutt-develop# docker build -t kutt .
Sending build context to Docker daemon  5.691MB
Step 1/6 : FROM node:9.5.0-alpine
 ---> e90a5bfd29f6
Step 2/6 : ADD . /code
 ---> e44e5649f481
Step 3/6 : WORKDIR /code
Removing intermediate container eb69d7a072ca
 ---> 868875b4b38d
Step 4/6 : RUN npm install
 ---> Running in 81b3115f1b7a
npm WARN notice [SECURITY] sshpk has the following vulnerability: 1 high. Go here for more details: https://nodesecurity.io/advisories?search=sshpk&version=1.13.1 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] hoek has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=hoek&version=2.16.3 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] stringstream has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=stringstream&version=0.0.5 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] randomatic has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=randomatic&version=1.1.7 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
npm WARN notice [SECURITY] base64url has the following vulnerability: 1 moderate. Go here for more details: https://nodesecurity.io/advisories?search=base64url&version=2.0.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> husky@0.15.0-rc.8 install /code/node_modules/husky
> node lib/installer/bin install

husky > failed to install
spawnSync git ENOENT

> uglifyjs-webpack-plugin@0.4.6 postinstall /code/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> styled-components@3.4.5 postinstall /code/node_modules/styled-components
> node ./scripts/postinstall.js || exit 0

Use styled-components at work? Consider supporting our development efforts at opencollective.com/styled-components
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 1151 packages in 47.442s
Removing intermediate container 81b3115f1b7a
 ---> 38a0ca59b3dc
Step 5/6 : RUN npm run build
 ---> Running in 1af65dd0deff

> kutt@1.0.0 build /code
> next build ./client

> Using external babel configuration
> Location: "/code/.babelrc"
> Failed to build
{ Error: (client) ./client/components/BodyWrapper/BodyWrapper.js
Module not found: Error: Can't resolve '../../config' in '/code/client/components/BodyWrapper'
resolve '../../config' in '/code/client/components/BodyWrapper'
  using description file: /code/package.json (relative path: ./client/components/BodyWrapper)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /code/package.json (relative path: ./client/components/BodyWrapper)
    using description file: /code/package.json (relative path: ./client/config)
      no extension
        Field 'browser' doesn't contain a valid alias configuration
        /code/client/config doesn't exist
      .js
        Field 'browser' doesn't contain a valid alias configuration
        /code/client/config.js doesn't exist
      .jsx
        Field 'browser' doesn't contain a valid alias configuration
        /code/client/config.jsx doesn't exist
      .json
        Field 'browser' doesn't contain a valid alias configuration
        /code/client/config.json doesn't exist
      as directory
        /code/client/config doesn't exist
[/code/client/config]
[/code/client/config.js]
[/code/client/config.jsx]
[/code/client/config.json]
[/code/client/config]
 @ ./client/components/BodyWrapper/BodyWrapper.js 41:14-37
 @ ./client/components/BodyWrapper/index.js
 @ ./client/pages/login.js
 @ multi ./pages/login.js
    at /code/node_modules/next/dist/server/build/index.js:162:31
    at runWithDependencies (/code/node_modules/webpack/lib/MultiCompiler.js:154:4)
    at /code/node_modules/async/dist/async.js:1126:9
    at /code/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/code/node_modules/async/dist/async.js:1050:13)
    at /code/node_modules/async/dist/async.js:958:16
    at /code/node_modules/async/dist/async.js:1123:13
    at runCompilers (/code/node_modules/webpack/lib/MultiCompiler.js:96:47)
    at fn (/code/node_modules/webpack/lib/MultiCompiler.js:101:6)
    at compiler.run (/code/node_modules/webpack/lib/MultiCompiler.js:150:5)
    at emitRecords.err (/code/node_modules/webpack/lib/Compiler.js:265:13)
    at Compiler.emitRecords (/code/node_modules/webpack/lib/Compiler.js:371:38)
    at emitAssets.err (/code/node_modules/webpack/lib/Compiler.js:258:10)
    at applyPluginsAsyncSeries1.err (/code/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/code/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/code/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
  errors: 
   [ '(client) ./client/components/BodyWrapper/BodyWrapper.js\nModule not found: Error: Can\'t resolve \'../../config\' in \'/code/client/components/BodyWrapper\'\nresolve \'../../config\' in \'/code/client/components/BodyWrapper\'\n  using description file: /code/package.json (relative path: ./client/components/BodyWrapper)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /code/package.json (relative path: ./client/components/BodyWrapper)\n    using description file: /code/package.json (relative path: ./client/config)\n      no extension\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config doesn\'t exist\n      .js\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.js doesn\'t exist\n      .jsx\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.jsx doesn\'t exist\n      .json\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.json doesn\'t exist\n      as directory\n        /code/client/config doesn\'t exist\n[/code/client/config]\n[/code/client/config.js]\n[/code/client/config.jsx]\n[/code/client/config.json]\n[/code/client/config]\n @ ./client/components/BodyWrapper/BodyWrapper.js 41:14-37\n @ ./client/components/BodyWrapper/index.js\n @ ./client/pages/login.js\n @ multi ./pages/login.js',
     '(client) ./client/components/Footer/ReCaptcha.js\nModule not found: Error: Can\'t resolve \'../../config\' in \'/code/client/components/Footer\'\nresolve \'../../config\' in \'/code/client/components/Footer\'\n  using description file: /code/package.json (relative path: ./client/components/Footer)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /code/package.json (relative path: ./client/components/Footer)\n    using description file: /code/package.json (relative path: ./client/config)\n      no extension\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config doesn\'t exist\n      .js\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.js doesn\'t exist\n      .jsx\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.jsx doesn\'t exist\n      .json\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.json doesn\'t exist\n      as directory\n        /code/client/config doesn\'t exist\n[/code/client/config]\n[/code/client/config.js]\n[/code/client/config.jsx]\n[/code/client/config.json]\n[/code/client/config]\n @ ./client/components/Footer/ReCaptcha.js 15:14-37\n @ ./client/components/Footer/Footer.js\n @ ./client/pages/index.js\n @ multi ./pages/index.js',
     '(client) ./client/helpers/analytics.js\nModule not found: Error: Can\'t resolve \'../config\' in \'/code/client/helpers\'\nresolve \'../config\' in \'/code/client/helpers\'\n  using description file: /code/package.json (relative path: ./client/helpers)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /code/package.json (relative path: ./client/helpers)\n    using description file: /code/package.json (relative path: ./client/config)\n      no extension\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config doesn\'t exist\n      .js\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.js doesn\'t exist\n      .jsx\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.jsx doesn\'t exist\n      .json\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.json doesn\'t exist\n      as directory\n        /code/client/config doesn\'t exist\n[/code/client/config]\n[/code/client/config.js]\n[/code/client/config.jsx]\n[/code/client/config.json]\n[/code/client/config]\n @ ./client/helpers/analytics.js 12:14-34\n @ ./client/components/BodyWrapper/BodyWrapper.js\n @ ./client/components/BodyWrapper/index.js\n @ ./client/pages/login.js\n @ multi ./pages/login.js',
     '(client) ./client/pages/report.js\nModule not found: Error: Can\'t resolve \'../config\' in \'/code/client/pages\'\nresolve \'../config\' in \'/code/client/pages\'\n  using description file: /code/package.json (relative path: ./client/pages)\n    Field \'browser\' doesn\'t contain a valid alias configuration\n  after using description file: /code/package.json (relative path: ./client/pages)\n    using description file: /code/package.json (relative path: ./client/config)\n      no extension\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config doesn\'t exist\n      .js\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.js doesn\'t exist\n      .jsx\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.jsx doesn\'t exist\n      .json\n        Field \'browser\' doesn\'t contain a valid alias configuration\n        /code/client/config.json doesn\'t exist\n      as directory\n        /code/client/config doesn\'t exist\n[/code/client/config]\n[/code/client/config.js]\n[/code/client/config.jsx]\n[/code/client/config.json]\n[/code/client/config]\n @ ./client/pages/report.js 29:14-34\n @ multi ./pages/report.js',
     '(server) ./client/components/BodyWrapper/BodyWrapper.js\nModule not found: Error: Can\'t resolve \'../../config\' in \'/code/client/components/BodyWrapper\'\nresolve \'../../config\' in \'/code/client/components/BodyWrapper\'\n  using description file: /code/package.json (relative path: ./client/components/BodyWrapper)\n  after using description file: /code/package.json (relative path: ./client/components/BodyWrapper)\n    using description file: /code/package.json (relative path: ./client/config)\n      no extension\n        /code/client/config doesn\'t exist\n      .js\n        /code/client/config.js doesn\'t exist\n      .jsx\n        /code/client/config.jsx doesn\'t exist\n      .json\n        /code/client/config.json doesn\'t exist\n      as directory\n        /code/client/config doesn\'t exist\n[/code/client/config]\n[/code/client/config.js]\n[/code/client/config.jsx]\n[/code/client/config.json]\n[/code/client/config]\n @ ./client/components/BodyWrapper/BodyWrapper.js 41:14-37\n @ ./client/components/BodyWrapper/index.js\n @ ./client/pages/index.js\n @ multi ./pages/index.js',
     '(server) ./client/components/Footer/ReCaptcha.js\nModule not found: Error: Can\'t resolve \'../../config\' in \'/code/client/components/Footer\'\nresolve \'../../config\' in \'/code/client/components/Footer\'\n  using description file: /code/package.json (relative path: ./client/components/Footer)\n  after using description file: /code/package.json (relative path: ./client/components/Footer)\n    using description file: /code/package.json (relative path: ./client/config)\n      no extension\n        /code/client/config doesn\'t exist\n      .js\n        /code/client/config.js doesn\'t exist\n      .jsx\n        /code/client/config.jsx doesn\'t exist\n      .json\n        /code/client/config.json doesn\'t exist\n      as directory\n        /code/client/config doesn\'t exist\n[/code/client/config]\n[/code/client/config.js]\n[/code/client/config.jsx]\n[/code/client/config.json]\n[/code/client/config]\n @ ./client/components/Footer/ReCaptcha.js 15:14-37\n @ ./client/components/Footer/Footer.js\n @ ./client/pages/index.js\n @ multi ./pages/index.js',
     '(server) ./client/helpers/analytics.js\nModule not found: Error: Can\'t resolve \'../config\' in \'/code/client/helpers\'\nresolve \'../config\' in \'/code/client/helpers\'\n  using description file: /code/package.json (relative path: ./client/helpers)\n  after using description file: /code/package.json (relative path: ./client/helpers)\n    using description file: /code/package.json (relative path: ./client/config)\n      no extension\n        /code/client/config doesn\'t exist\n      .js\n        /code/client/config.js doesn\'t exist\n      .jsx\n        /code/client/config.jsx doesn\'t exist\n      .json\n        /code/client/config.json doesn\'t exist\n      as directory\n        /code/client/config doesn\'t exist\n[/code/client/config]\n[/code/client/config.js]\n[/code/client/config.jsx]\n[/code/client/config.json]\n[/code/client/config]\n @ ./client/helpers/analytics.js 12:14-34\n @ ./client/components/BodyWrapper/BodyWrapper.js\n @ ./client/components/BodyWrapper/index.js\n @ ./client/pages/index.js\n @ multi ./pages/index.js',
     '(server) ./client/pages/report.js\nModule not found: Error: Can\'t resolve \'../config\' in \'/code/client/pages\'\nresolve \'../config\' in \'/code/client/pages\'\n  using description file: /code/package.json (relative path: ./client/pages)\n  after using description file: /code/package.json (relative path: ./client/pages)\n    using description file: /code/package.json (relative path: ./client/config)\n      no extension\n        /code/client/config doesn\'t exist\n      .js\n        /code/client/config.js doesn\'t exist\n      .jsx\n        /code/client/config.jsx doesn\'t exist\n      .json\n        /code/client/config.json doesn\'t exist\n      as directory\n        /code/client/config doesn\'t exist\n[/code/client/config]\n[/code/client/config.js]\n[/code/client/config.jsx]\n[/code/client/config.json]\n[/code/client/config]\n @ ./client/pages/report.js 29:14-34\n @ multi ./pages/report.js' ],
  warnings: [] }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! kutt@1.0.0 build: `next build ./client`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the kutt@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-23T19_24_27_440Z-debug.log
The command '/bin/sh -c npm run build' returned a non-zero code: 1
```

**Comment by poeti8** [comment]
You need to create and fill both config files (inside client and server folder).
